/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVentesRouteImport } from './routes/app.ventes'
import { Route as AppTresorerieRouteImport } from './routes/app.tresorerie'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppRapportsRouteImport } from './routes/app.rapports'
import { Route as AppPersonnelRouteImport } from './routes/app.personnel'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppFournisseursRouteImport } from './routes/app.fournisseurs'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDepensesRouteImport } from './routes/app.depenses'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppRestoTablesRouteImport } from './routes/app.resto.tables'
import { Route as AppRestoMenuRouteImport } from './routes/app.resto.menu'
import { Route as AppRestoCuisineRouteImport } from './routes/app.resto.cuisine'
import { Route as AppRestoCommandesRouteImport } from './routes/app.resto.commandes'
import { Route as AppElecGarantiesRouteImport } from './routes/app.elec.garanties'
import { Route as AppElecFacturationRouteImport } from './routes/app.elec.facturation'
import { Route as AppElecCreditsRouteImport } from './routes/app.elec.credits'
import { Route as AppAutoVehiculesRouteImport } from './routes/app.auto.vehicules'
import { Route as AppAutoLocationsRouteImport } from './routes/app.auto.locations'
import { Route as AppAutoGpsRouteImport } from './routes/app.auto.gps'
import { Route as AppAutoCreditsRouteImport } from './routes/app.auto.credits'

const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/app/ventes',
  path: '/app/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTresorerieRoute = AppTresorerieRouteImport.update({
  id: '/app/tresorerie',
  path: '/app/tresorerie',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/app/rapports',
  path: '/app/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPersonnelRoute = AppPersonnelRouteImport.update({
  id: '/app/personnel',
  path: '/app/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/app/parametres',
  path: '/app/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFournisseursRoute = AppFournisseursRouteImport.update({
  id: '/app/fournisseurs',
  path: '/app/fournisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/app/documents',
  path: '/app/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDepensesRoute = AppDepensesRouteImport.update({
  id: '/app/depenses',
  path: '/app/depenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/app/clients',
  path: '/app/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoTablesRoute = AppRestoTablesRouteImport.update({
  id: '/app/resto/tables',
  path: '/app/resto/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoMenuRoute = AppRestoMenuRouteImport.update({
  id: '/app/resto/menu',
  path: '/app/resto/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoCuisineRoute = AppRestoCuisineRouteImport.update({
  id: '/app/resto/cuisine',
  path: '/app/resto/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoCommandesRoute = AppRestoCommandesRouteImport.update({
  id: '/app/resto/commandes',
  path: '/app/resto/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppElecGarantiesRoute = AppElecGarantiesRouteImport.update({
  id: '/app/elec/garanties',
  path: '/app/elec/garanties',
  getParentRoute: () => rootRouteImport,
} as any)
const AppElecFacturationRoute = AppElecFacturationRouteImport.update({
  id: '/app/elec/facturation',
  path: '/app/elec/facturation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppElecCreditsRoute = AppElecCreditsRouteImport.update({
  id: '/app/elec/credits',
  path: '/app/elec/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutoVehiculesRoute = AppAutoVehiculesRouteImport.update({
  id: '/app/auto/vehicules',
  path: '/app/auto/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutoLocationsRoute = AppAutoLocationsRouteImport.update({
  id: '/app/auto/locations',
  path: '/app/auto/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutoGpsRoute = AppAutoGpsRouteImport.update({
  id: '/app/auto/gps',
  path: '/app/auto/gps',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAutoCreditsRoute = AppAutoCreditsRouteImport.update({
  id: '/app/auto/credits',
  path: '/app/auto/credits',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/personnel': typeof AppPersonnelRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/tresorerie': typeof AppTresorerieRoute
  '/app/ventes': typeof AppVentesRoute
  '/app/': typeof AppIndexRoute
  '/app/auto/credits': typeof AppAutoCreditsRoute
  '/app/auto/gps': typeof AppAutoGpsRoute
  '/app/auto/locations': typeof AppAutoLocationsRoute
  '/app/auto/vehicules': typeof AppAutoVehiculesRoute
  '/app/elec/credits': typeof AppElecCreditsRoute
  '/app/elec/facturation': typeof AppElecFacturationRoute
  '/app/elec/garanties': typeof AppElecGarantiesRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/tables': typeof AppRestoTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/personnel': typeof AppPersonnelRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/tresorerie': typeof AppTresorerieRoute
  '/app/ventes': typeof AppVentesRoute
  '/app': typeof AppIndexRoute
  '/app/auto/credits': typeof AppAutoCreditsRoute
  '/app/auto/gps': typeof AppAutoGpsRoute
  '/app/auto/locations': typeof AppAutoLocationsRoute
  '/app/auto/vehicules': typeof AppAutoVehiculesRoute
  '/app/elec/credits': typeof AppElecCreditsRoute
  '/app/elec/facturation': typeof AppElecFacturationRoute
  '/app/elec/garanties': typeof AppElecGarantiesRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/tables': typeof AppRestoTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/clients': typeof AppClientsRoute
  '/app/depenses': typeof AppDepensesRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/fournisseurs': typeof AppFournisseursRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/personnel': typeof AppPersonnelRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/tresorerie': typeof AppTresorerieRoute
  '/app/ventes': typeof AppVentesRoute
  '/app/': typeof AppIndexRoute
  '/app/auto/credits': typeof AppAutoCreditsRoute
  '/app/auto/gps': typeof AppAutoGpsRoute
  '/app/auto/locations': typeof AppAutoLocationsRoute
  '/app/auto/vehicules': typeof AppAutoVehiculesRoute
  '/app/elec/credits': typeof AppElecCreditsRoute
  '/app/elec/facturation': typeof AppElecFacturationRoute
  '/app/elec/garanties': typeof AppElecGarantiesRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/tables': typeof AppRestoTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/clients'
    | '/app/depenses'
    | '/app/documents'
    | '/app/fournisseurs'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/personnel'
    | '/app/rapports'
    | '/app/stock'
    | '/app/tresorerie'
    | '/app/ventes'
    | '/app/'
    | '/app/auto/credits'
    | '/app/auto/gps'
    | '/app/auto/locations'
    | '/app/auto/vehicules'
    | '/app/elec/credits'
    | '/app/elec/facturation'
    | '/app/elec/garanties'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/menu'
    | '/app/resto/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/clients'
    | '/app/depenses'
    | '/app/documents'
    | '/app/fournisseurs'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/personnel'
    | '/app/rapports'
    | '/app/stock'
    | '/app/tresorerie'
    | '/app/ventes'
    | '/app'
    | '/app/auto/credits'
    | '/app/auto/gps'
    | '/app/auto/locations'
    | '/app/auto/vehicules'
    | '/app/elec/credits'
    | '/app/elec/facturation'
    | '/app/elec/garanties'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/menu'
    | '/app/resto/tables'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/clients'
    | '/app/depenses'
    | '/app/documents'
    | '/app/fournisseurs'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/personnel'
    | '/app/rapports'
    | '/app/stock'
    | '/app/tresorerie'
    | '/app/ventes'
    | '/app/'
    | '/app/auto/credits'
    | '/app/auto/gps'
    | '/app/auto/locations'
    | '/app/auto/vehicules'
    | '/app/elec/credits'
    | '/app/elec/facturation'
    | '/app/elec/garanties'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/menu'
    | '/app/resto/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDepensesRoute: typeof AppDepensesRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFournisseursRoute: typeof AppFournisseursRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppParametresRoute: typeof AppParametresRoute
  AppPersonnelRoute: typeof AppPersonnelRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppStockRoute: typeof AppStockRoute
  AppTresorerieRoute: typeof AppTresorerieRoute
  AppVentesRoute: typeof AppVentesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAutoCreditsRoute: typeof AppAutoCreditsRoute
  AppAutoGpsRoute: typeof AppAutoGpsRoute
  AppAutoLocationsRoute: typeof AppAutoLocationsRoute
  AppAutoVehiculesRoute: typeof AppAutoVehiculesRoute
  AppElecCreditsRoute: typeof AppElecCreditsRoute
  AppElecFacturationRoute: typeof AppElecFacturationRoute
  AppElecGarantiesRoute: typeof AppElecGarantiesRoute
  AppRestoCommandesRoute: typeof AppRestoCommandesRoute
  AppRestoCuisineRoute: typeof AppRestoCuisineRoute
  AppRestoMenuRoute: typeof AppRestoMenuRoute
  AppRestoTablesRoute: typeof AppRestoTablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ventes': {
      id: '/app/ventes'
      path: '/app/ventes'
      fullPath: '/app/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tresorerie': {
      id: '/app/tresorerie'
      path: '/app/tresorerie'
      fullPath: '/app/tresorerie'
      preLoaderRoute: typeof AppTresorerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rapports': {
      id: '/app/rapports'
      path: '/app/rapports'
      fullPath: '/app/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/personnel': {
      id: '/app/personnel'
      path: '/app/personnel'
      fullPath: '/app/personnel'
      preLoaderRoute: typeof AppPersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/app/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/fournisseurs': {
      id: '/app/fournisseurs'
      path: '/app/fournisseurs'
      fullPath: '/app/fournisseurs'
      preLoaderRoute: typeof AppFournisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/app/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/depenses': {
      id: '/app/depenses'
      path: '/app/depenses'
      fullPath: '/app/depenses'
      preLoaderRoute: typeof AppDepensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/app/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/tables': {
      id: '/app/resto/tables'
      path: '/app/resto/tables'
      fullPath: '/app/resto/tables'
      preLoaderRoute: typeof AppRestoTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/menu': {
      id: '/app/resto/menu'
      path: '/app/resto/menu'
      fullPath: '/app/resto/menu'
      preLoaderRoute: typeof AppRestoMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/cuisine': {
      id: '/app/resto/cuisine'
      path: '/app/resto/cuisine'
      fullPath: '/app/resto/cuisine'
      preLoaderRoute: typeof AppRestoCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/commandes': {
      id: '/app/resto/commandes'
      path: '/app/resto/commandes'
      fullPath: '/app/resto/commandes'
      preLoaderRoute: typeof AppRestoCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/elec/garanties': {
      id: '/app/elec/garanties'
      path: '/app/elec/garanties'
      fullPath: '/app/elec/garanties'
      preLoaderRoute: typeof AppElecGarantiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/elec/facturation': {
      id: '/app/elec/facturation'
      path: '/app/elec/facturation'
      fullPath: '/app/elec/facturation'
      preLoaderRoute: typeof AppElecFacturationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/elec/credits': {
      id: '/app/elec/credits'
      path: '/app/elec/credits'
      fullPath: '/app/elec/credits'
      preLoaderRoute: typeof AppElecCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auto/vehicules': {
      id: '/app/auto/vehicules'
      path: '/app/auto/vehicules'
      fullPath: '/app/auto/vehicules'
      preLoaderRoute: typeof AppAutoVehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auto/locations': {
      id: '/app/auto/locations'
      path: '/app/auto/locations'
      fullPath: '/app/auto/locations'
      preLoaderRoute: typeof AppAutoLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auto/gps': {
      id: '/app/auto/gps'
      path: '/app/auto/gps'
      fullPath: '/app/auto/gps'
      preLoaderRoute: typeof AppAutoGpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auto/credits': {
      id: '/app/auto/credits'
      path: '/app/auto/credits'
      fullPath: '/app/auto/credits'
      preLoaderRoute: typeof AppAutoCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  AppClientsRoute: AppClientsRoute,
  AppDepensesRoute: AppDepensesRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFournisseursRoute: AppFournisseursRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppParametresRoute: AppParametresRoute,
  AppPersonnelRoute: AppPersonnelRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppStockRoute: AppStockRoute,
  AppTresorerieRoute: AppTresorerieRoute,
  AppVentesRoute: AppVentesRoute,
  AppIndexRoute: AppIndexRoute,
  AppAutoCreditsRoute: AppAutoCreditsRoute,
  AppAutoGpsRoute: AppAutoGpsRoute,
  AppAutoLocationsRoute: AppAutoLocationsRoute,
  AppAutoVehiculesRoute: AppAutoVehiculesRoute,
  AppElecCreditsRoute: AppElecCreditsRoute,
  AppElecFacturationRoute: AppElecFacturationRoute,
  AppElecGarantiesRoute: AppElecGarantiesRoute,
  AppRestoCommandesRoute: AppRestoCommandesRoute,
  AppRestoCuisineRoute: AppRestoCuisineRoute,
  AppRestoMenuRoute: AppRestoMenuRoute,
  AppRestoTablesRoute: AppRestoTablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
