/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVentesRouteImport } from './routes/app.ventes'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppRapportsRouteImport } from './routes/app.rapports'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppClientsRouteImport } from './routes/app.clients'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/app/ventes',
  path: '/app/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/app/rapports',
  path: '/app/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/app/parametres',
  path: '/app/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/app/clients',
  path: '/app/clients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/clients': typeof AppClientsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/clients': typeof AppClientsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/clients': typeof AppClientsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/clients'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/rapports'
    | '/app/stock'
    | '/app/ventes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/clients'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/rapports'
    | '/app/stock'
    | '/app/ventes'
  id:
    | '__root__'
    | '/'
    | '/app/clients'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/rapports'
    | '/app/stock'
    | '/app/ventes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppClientsRoute: typeof AppClientsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppParametresRoute: typeof AppParametresRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppStockRoute: typeof AppStockRoute
  AppVentesRoute: typeof AppVentesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ventes': {
      id: '/app/ventes'
      path: '/app/ventes'
      fullPath: '/app/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rapports': {
      id: '/app/rapports'
      path: '/app/rapports'
      fullPath: '/app/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/app/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/app/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppClientsRoute: AppClientsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppParametresRoute: AppParametresRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppStockRoute: AppStockRoute,
  AppVentesRoute: AppVentesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
