/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVentesRouteImport } from './routes/app.ventes'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppRapportsRouteImport } from './routes/app.rapports'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppRestoTablesRouteImport } from './routes/app.resto.tables'
import { Route as AppRestoMenuRouteImport } from './routes/app.resto.menu'
import { Route as AppRestoCuisineRouteImport } from './routes/app.resto.cuisine'
import { Route as AppRestoCommandesRouteImport } from './routes/app.resto.commandes'

const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/app/ventes',
  path: '/app/ventes',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRapportsRoute = AppRapportsRouteImport.update({
  id: '/app/rapports',
  path: '/app/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/app/parametres',
  path: '/app/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/app/clients',
  path: '/app/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoTablesRoute = AppRestoTablesRouteImport.update({
  id: '/app/resto/tables',
  path: '/app/resto/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoMenuRoute = AppRestoMenuRouteImport.update({
  id: '/app/resto/menu',
  path: '/app/resto/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoCuisineRoute = AppRestoCuisineRouteImport.update({
  id: '/app/resto/cuisine',
  path: '/app/resto/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestoCommandesRoute = AppRestoCommandesRouteImport.update({
  id: '/app/resto/commandes',
  path: '/app/resto/commandes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/clients': typeof AppClientsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
  '/app/': typeof AppIndexRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/tables': typeof AppRestoTablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/clients': typeof AppClientsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
  '/app': typeof AppIndexRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/tables': typeof AppRestoTablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/app/clients': typeof AppClientsRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/rapports': typeof AppRapportsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
  '/app/': typeof AppIndexRoute
  '/app/resto/commandes': typeof AppRestoCommandesRoute
  '/app/resto/cuisine': typeof AppRestoCuisineRoute
  '/app/resto/menu': typeof AppRestoMenuRoute
  '/app/resto/tables': typeof AppRestoTablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/clients'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/rapports'
    | '/app/stock'
    | '/app/ventes'
    | '/app/'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/menu'
    | '/app/resto/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/clients'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/rapports'
    | '/app/stock'
    | '/app/ventes'
    | '/app'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/menu'
    | '/app/resto/tables'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/inscription'
    | '/app/clients'
    | '/app/onboarding'
    | '/app/parametres'
    | '/app/rapports'
    | '/app/stock'
    | '/app/ventes'
    | '/app/'
    | '/app/resto/commandes'
    | '/app/resto/cuisine'
    | '/app/resto/menu'
    | '/app/resto/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  AppClientsRoute: typeof AppClientsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppParametresRoute: typeof AppParametresRoute
  AppRapportsRoute: typeof AppRapportsRoute
  AppStockRoute: typeof AppStockRoute
  AppVentesRoute: typeof AppVentesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRestoCommandesRoute: typeof AppRestoCommandesRoute
  AppRestoCuisineRoute: typeof AppRestoCuisineRoute
  AppRestoMenuRoute: typeof AppRestoMenuRoute
  AppRestoTablesRoute: typeof AppRestoTablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ventes': {
      id: '/app/ventes'
      path: '/app/ventes'
      fullPath: '/app/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rapports': {
      id: '/app/rapports'
      path: '/app/rapports'
      fullPath: '/app/rapports'
      preLoaderRoute: typeof AppRapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/app/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/app/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/tables': {
      id: '/app/resto/tables'
      path: '/app/resto/tables'
      fullPath: '/app/resto/tables'
      preLoaderRoute: typeof AppRestoTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/menu': {
      id: '/app/resto/menu'
      path: '/app/resto/menu'
      fullPath: '/app/resto/menu'
      preLoaderRoute: typeof AppRestoMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/cuisine': {
      id: '/app/resto/cuisine'
      path: '/app/resto/cuisine'
      fullPath: '/app/resto/cuisine'
      preLoaderRoute: typeof AppRestoCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resto/commandes': {
      id: '/app/resto/commandes'
      path: '/app/resto/commandes'
      fullPath: '/app/resto/commandes'
      preLoaderRoute: typeof AppRestoCommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  AppClientsRoute: AppClientsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppParametresRoute: AppParametresRoute,
  AppRapportsRoute: AppRapportsRoute,
  AppStockRoute: AppStockRoute,
  AppVentesRoute: AppVentesRoute,
  AppIndexRoute: AppIndexRoute,
  AppRestoCommandesRoute: AppRestoCommandesRoute,
  AppRestoCuisineRoute: AppRestoCuisineRoute,
  AppRestoMenuRoute: AppRestoMenuRoute,
  AppRestoTablesRoute: AppRestoTablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
